// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // Only needed for `prisma migrate dev` against a local `prisma dev` server, which
    // exposes its shadow DB on a separate port. Hosted Postgres (Neon) doesn't need it.
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
